spring:
  datasource:
    url: jdbc:mysql://localhost:3306/helloSpring?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: Adminadmin12!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true
#    database-platform:

logging:
  level:
    org.springframework.security: DEBUG
