spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clonemovie?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: tjddbs
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  data:
    redis:
      host: 127.0.0.1
      port: 6379

#    database-platform:
#    Upload file Setting
